services:
  api:
    ports:
      - "5002:5000"
    env_file:
      - .env.stage
    command: flask run --reload

  worker:
    env_file:
      - .env.stage

  beat:
    env_file:
      - .env.stage

  mongo:
    ports:
      - "27018:27017"
    env_file:
      - .env.stage
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}

  redis:
    ports:
      - "6380:6379"

  flower:
    image: mher/flower
    ports:
      - "5555:5555"
    env_file:
      - .env.stage
    command: celery --broker=${CELERY_BROKER_URL} flower --port=5555
    depends_on:
      - redis