version: '3.9'

services:

  mongo:
    image: mongo:6
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:7

  api:
    build: .
    depends_on:
      - mongo
      - redis

  worker:
    build: .
    depends_on:
      - redis
      - mongo
    command: celery -A celery_worker worker --loglevel=info

  beat:
    build: .
    depends_on:
      - redis
      - mongo
    command: celery -A celery_worker beat --loglevel=info

volumes:
  mongo-data:
