# k8s/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: animal-kb-config
  namespace: animal-kb
data:
  FLASK_ENV: "production"
  TZ: "Asia/Kolkata"
  # MongoDB connection URI
  MONGO_URI: "mongodb://{MONGO_INITDB_ROOT_USERNAME}:{MONGO_INITDB_ROOT_PASSWORD}@mongodb:27017"
  # Redis connection details
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
