# k8s/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: animalkb-config
  namespace: animalkb
data:
  FLASK_ENV: "production"
  TZ: "Asia/Kolkata"
  # MongoDB connection URI
  MONGO_URI: "mongodb://mongo:27017/animalkb"
  # Redis connection details
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
