apiVersion: v1
kind: Secret
metadata:
  name: animal-kb-secrets
  namespace: animal-kb
type: Opaque
stringData:
  FLASK_SECRET_KEY: "supersecretkey"   # replace with a real random key
  JWT_SECRET_KEY: "superjwtkey"       # replace with your JWT secret
  API_ENV: "production"
