apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: animalkb-ingress
  namespace: animalkb
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: animalkb.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: backend
            port:
              number: 8000
