# k8s/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: animalkb-secret
  namespace: animalkb
type: Opaque
stringData:
  SECRET_KEY: "replace-with-strong-secret"
  MONGO_INITDB_ROOT_USERNAME: "animalkb_admin"
  MONGO_INITDB_ROOT_PASSWORD: "verysecurepassword"
