# k8s/worker.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: animalkb
spec:
  replicas: 2
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: animalkb-worker:latest       # local image name
        imagePullPolicy: Never              # do not pull from registry
        envFrom:
        - configMapRef:
            name: animalkb-config
        - secretRef:
            name: animalkb-secret
        command: ["celery", "-A", "app.celery", "worker", "--loglevel=info"]
